#import "../prelude.typ": *
#show: chapter.with(title: [Quick start], id: <quick-start>)

== Scope <scope>

This manual describes the *abntly* package, which formats academic works written in
#link("https://typst.app")[Typst] according to the ABNT standards. The package is intended for final course works,
dissertations and theses. Other types of document, such as articles, technical reports and research projects, are
outside its scope.

The manual is based on ABNT NBR 14724:2024, which defines the structure and the general presentation rules of
academic works and refers to the other standards (@norms[Section]). For each element of the work, the manual
presents:

- what the standard requires, in summary;
- the function of the package that meets this requirement;
- an example of use, with the result.

The manual does not replace the text of the standards, which must be consulted in case of doubt.

== About the package <about>

abntly applies the ABNT formatting to the whole document through its main function, `abntly`
(@main-function[Section]), called only once at the top of the file. From that call on, the package sets up
automatically:

- the page format and the margins;
- the fonts and the spacing;
- the numbering of the pages and of the sections;
- the formatting of illustrations, tables and equations;
- the citations and the list of references.

The elements of the structure of the work, such as the cover, the title page and the abstracts, are created by
functions of their own, described in @structure[Chapter].

Every function has an English name and a Portuguese name (for example, `cover` and `capa`), with the parameters and
the documentation in the respective language. This manual uses the English names; the Portuguese version of the
manual uses the Portuguese ones. The two sets can be combined in the same document.

The language of the work does not depend on the names used. It is set in the `lang` parameter of the main function
(@main-function[Section]): a work written with the English names comes out in Portuguese, unless `lang: "en"` is
given.

== Standards implemented <norms>

The package implements the requirements of the standards listed below.

#data-table([Standards implemented by the package], (5.6cm, 1fr), ([Standard], [Purpose]),
  [*ABNT NBR 14724:2024* \ Trabalhos acadêmicos — Apresentação],
  [Defines the structure of the academic work and the general presentation rules: format, margins, spacing,
    pagination, illustrations and tables. It is the main standard; the others are cited by it. The package follows
    the corrected version of 2025.],
  [*ABNT NBR 6024:2012* \ Numeração progressiva das seções de um documento — Apresentação],
  [Defines the numbering of the sections, the items and the subitems.],
  [*ABNT NBR 6027:2012* \ Sumário — Apresentação],
  [Defines the presentation of the table of contents.],
  [*ABNT NBR 6028:2021* \ Resumo, resenha e recensão — Apresentação],
  [Defines the writing and the presentation of the abstract and of the keywords.],
  [*ABNT NBR 10520:2023* \ Citações em documentos — Apresentação],
  [Defines the presentation of the citations: the author-date and numeric citation systems, the direct and
    indirect citations and the notes.],
  [*ABNT NBR 6023:2025* \ Referências — Elaboração],
  [Defines the elements of the references, their order and their form of presentation.],
  [*ABNT NBR 6034:2004* \ Índice — Apresentação],
  [Defines the presentation of the index.],
  [*ABNT NBR 6033:1989* \ Ordem alfabética],
  [Defines the criteria of alphabetical ordering, used in the lists, in the glossary and in the index.],
  [*IBGE (1993)* \ Normas de apresentação tabular],
  [Defines the presentation of the tables, as indicated by NBR 14724.],
)

== Installation <install>

The package requires Typst #package.compiler or later. To use it, add the following line at the top of the file:

```typ
#import "@preview/abntly:0.1.0": *
```

Typst downloads the package automatically on the first compilation.

To create a new work from the template of the package, which has every element of the structure with comments, use
the command:

```sh
typst init @preview/abntly:0.1.0
```

== Dependencies <dependencies>

abntly depends on other Typst packages and on the fonts of the *New Computer Modern* family. The packages are
downloaded automatically along with abntly. Some of the fonts come with Typst; the others must be installed.

#data-table([Dependencies of the package], (5cm, 1.6cm, 1fr), ([Dependency], [Type], [Use]),
  ..dependencies.map(((name, version)) => ([#raw(name) #version], [Package], (
    equate: [Numbering of the equations and of the lines of an equation.],
    glossarium: [Acronyms, symbols and glossary terms cited in the text by a key.],
    linguify: [Terms generated by the package, in the language of the text.],
    subpar: [Subfigures.],
  ).at(name))).flatten(),
  [New Computer Modern], [Font], [Text. Comes with Typst.],
  [New Computer Modern Math], [Font], [Equations. Comes with Typst.],
  [New Computer Modern Sans], [Font], [Headings. Must be installed.],
  [New Computer Modern Mono], [Font], [Code. Must be installed.],
  [New Computer Modern 08], [Font], [Superscripts and subscripts. Must be installed.],
)

To install the fonts that do not come with Typst:

+ download the package #link("https://ctan.org/pkg/newcomputermodern")[`newcomputermodern`] from CTAN;
+ in the `otf` folder, install the files `NewCM10-*`, `NewCM08-*`, `NewCMSans10-*`, `NewCMSans08-*`, `NewCMMono10-*`
  and `NewCMMath-*` (the files with `Book` in their name are not used);
+ on #link("https://typst.app")[typst.app], upload these files to the project instead of installing them.

#remark[
  Without these fonts, the document is compiled with fallback fonts, and Typst issues a warning for each missing
  family, such as `unknown font family: new computer modern sans`.
]

== Main function <main-function>

The function `abntly` is the main function of the package. It applies the ABNT formatting to the whole document and
must be used with a `show` rule, right after the import. The data of the work are given in the `info` parameter
(@work-data[Section]).

The following example creates a work with a cover, a title page, a table of contents and one chapter:

#page-example("first-work", pages: (1, 2, 4))

The other parameters set the language, two-sided printing, the colour of the links, the font size of the tables,
the numbering of the equations and the citation system. The default language is Portuguese; the examples of this
manual are works in English, so they pass `lang: "en"`.

Settings that are not parameters of the function can be changed with Typst `set` rules after the call. For
example, `#set text(size: 11pt)` changes the font size, and the other sizes scale with it.

#reference("abntly", "dark-indigo")

#reference("config-names", description: true)

== Conventions of the manual <how-to-read>

Each element is presented in up to four blocks. The first one summarises what the standard requires:

#norm-box("NBR 14724:2024, 5.1", "required", "implemented")[
  The text must be presented in black; other colours may be used only in the illustrations. If printed, the work
  must use white or recycled paper, in A4 format.
]

The pills show the status of the element in the standard (#pill("required"), #pill("optional") or
#pill("recommended")) and in the package (#pill("implemented") or #pill("partial")). The pill
#pill("decision") marks a point that the standard does not define and that was decided by the package, such as the
font or the position of an element on the page.

The second block is an example, with the code and the result, like the one that follows. The examples of whole
pages show the pages generated.

```example
#figure(caption: [Distribution by region])[
  #rect(width: 6cm, height: 2cm)
  #source()
]
```

Remarks appear in boxes like this one:

#remark[
  A remark points out a caution of use, a limitation of the package or a choice that depends on the institution.
]

The last block is the reference of the function, with the signature, the type and the default value of each
parameter and the description of each one.
